apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: aksplatform-keyvault
  namespace: app

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"

    clientID: "<WORKLOAD_IDENTITY_CLIENT_ID>"

    keyvaultName: "kv-aksplatform-dev-ne"

    cloudName: ""

    objects: |
      array:
        - |
          objectName: test-secret
          objectType: secret
          objectVersion: ""

    tenantId: "00000000-0000-0000-0000-000000000000"
