apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: kv-reader

      containers:
        - name: backend

          image: acraksplatformdevne.azurecr.io/backend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
              protocol: TCP

          env:
            - name: APP_ENV
              value: "dev"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 15
            periodSeconds: 20

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store

          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true

            volumeAttributes:
              secretProviderClass: "aksplatform-keyvault"
